# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='location',
        ),
    ]
